language: android
jdk: oraclejdk7
android:
  components:
    # The BuildTools version used by your project
    - tools
    - build-tools-23.0.2 # 23.0.2 was not available on build
    - build-tools-23.0.1
    - build-tools-20.0.0
    # The SDK version used to compile your project
    - android-24
    - android-23
    - android-22
    - android-21
    - android-19
    - android-18
    - android-15
    - android-10
    - android-8
    - addon-google_apis-google-10
    - addon-google_apis-google-15
    - addon-google_apis-google-18
    - addon-google_apis-google-19
    - addon-google_apis-google-21
    - addon-google_apis-google-22
    - addon-google_apis-google-23
    - addon-google_apis-google-8

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-android-8
    - sys-img-armeabi-android-10
    - sys-img-armeabi-android-15
    - sys-img-armeabi-android-19
    - sys-img-armeabi-android-21
    - sys-img-x86-android-22
    - sys-img-x86-android-23
    - addon-google_apis-google-23

sudo: required

# fun fact, travis doesn't really support multiple AVDs running currently for a single build (tried it, build timed out constantly while starting up the AVDs)
# thus we're using a build matrix (which makes more sense anyhow)
env:
    global:
    #minutes (2 minutes by default), prevents CommandShellUnresponsiveExceptions
    - ADB_INSTALL_TIMEOUT=14

    matrix:
    #note when changing these, updating the gradle build file for the GoogleWrapper project
    # first env var is just for display purposes
    #api8 with google
    - API=8g ANDROID_TARGET=12  ANDROID_ABI=armeabi
    #api8
    - API=8 ANDROID_TARGET=1  ANDROID_ABI=armeabi
    #api10
    - API=10 ANDROID_TARGET=2  ANDROID_ABI=armeabi
    #api10 with google
    - API=10g ANDROID_TARGET=13  ANDROID_ABI=armeabi
    #api15
    - API=15 ANDROID_TARGET=3  ANDROID_ABI=armeabi-v7a
    #api15 with google
    - API=15g ANDROID_TARGET=14  ANDROID_ABI=armeabi-v7a
    #api19
    - API=19 ANDROID_TARGET=7  ANDROID_ABI=armeabi-v7a
    #api19 with google
    - API=19g ANDROID_TARGET=16  ANDROID_ABI=armeabi-v7a
    #api21
    #- ANDROID_TARGET=17  ANDROID_ABI=armeabi-v7a no abi available with google apis
    #api22
    # ANDROID_TARGET=18  ANDROID_ABI=x86 not currently possible with travis, missing some kind of hardware acceleration driver
    #api23
    # ANDROID_TARGET=19  ANDROID_ABI=x86 not currently possible with travis, missing some kind of hardware acceleration driver

before_install:
  # create and start emulators
  - android list targets
  - echo no | android create avd --force -n test$ANDROID_TARGET -t $ANDROID_TARGET --abi $ANDROID_ABI --sdcard 100M
  - emulator -memory 1536 -avd test$ANDROID_TARGET -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

# mvn sdk deploy
before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

#build
script:
  #build using gradle
  - ./gradlew -version
  - ./gradlew clean connectedCheck
  # fun fact, maven runs android tests concurrently for all connected devices, gradle does not
  # since we're using build matrix, each build target compiles the source, fires up it's specific vm, runs the tests, then exits.
  # --stacktrace
